apiVersion: v1
items:
- apiVersion: v1
  data:
    connection_string: YW1xcDovL2RlZmF1bHRfdXNlcl9DTmJDbXp4czcyVk5IeEx1RmxMOlFxWVQ2VGN1Sk92Y0I0QWJ2M1pMS2ZFZ1BNeDZISnZEQHJhYmJpdG1xLm1pY3Jvc2VydmljZXMuc3ZjOjU2NzIv
    default_user.conf: ZGVmYXVsdF91c2VyID0gZGVmYXVsdF91c2VyX0NOYkNtenhzNzJWTkh4THVGbEwKZGVmYXVsdF9wYXNzID0gUXFZVDZUY3VKT3ZjQjRBYnYzWkxLZkVnUE14NkhKdkQK
    host: cmFiYml0bXEubWljcm9zZXJ2aWNlcy5zdmM=
    password: UXFZVDZUY3VKT3ZjQjRBYnYzWkxLZkVnUE14NkhKdkQ=
    port: NTY3Mg==
    provider: cmFiYml0bXE=
    type: cmFiYml0bXE=
    username: ZGVmYXVsdF91c2VyX0NOYkNtenhzNzJWTkh4THVGbEw=
  kind: Secret
  metadata:
    creationTimestamp: "2026-04-14T03:42:32Z"
    labels:
      app.kubernetes.io/component: rabbitmq
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/part-of: rabbitmq
    name: rabbitmq-default-user
    namespace: microservices
    ownerReferences:
    - apiVersion: rabbitmq.com/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: RabbitmqCluster
      name: rabbitmq
      uid: 36a194aa-1d93-4370-ab6f-18e4a3102e13
    resourceVersion: "357260"
    uid: ef958eb1-53a6-43c0-a6eb-cfbc4ff9a14e
  type: Opaque
- apiVersion: v1
  data:
    .erlang.cookie: SDU1ZXVReGljdWJnMFZUV2tsbnhtSXZJQ1ZWakRpMTk=
  kind: Secret
  metadata:
    creationTimestamp: "2026-04-14T03:42:31Z"
    labels:
      app.kubernetes.io/component: rabbitmq
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/part-of: rabbitmq
    name: rabbitmq-erlang-cookie
    namespace: microservices
    ownerReferences:
    - apiVersion: rabbitmq.com/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: RabbitmqCluster
      name: rabbitmq
      uid: 36a194aa-1d93-4370-ab6f-18e4a3102e13
    resourceVersion: "357254"
    uid: ace4f061-8cd7-4a78-a240-a3f65a43e467
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
