spring.application.name=multiplication
# Gives us access to the H2 database web console
spring.h2.console.enabled=true
# Creates the database in a file
spring.datasource.url=jdbc:h2:file:~/multiplication;AUTO_SERVER=TRUE
# Creates or updates the schema if needed
spring.jpa.hibernate.ddl-auto=update
# For educational purposes we will show the SQL in console
# spring.jpa.show-sql=true

# Gamification service URL
service.gamification.host=http://localhost:8081

amqp.exchange.attempts=attempts.topic
spring.rabbitmq.host=localhost
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# Shows declaration of exchanges, queues, bindings, etc.
logging.level.org.springframework.amqp.rabbit.core.RabbitAdmin=DEBUG
spring.config.import=optional:consul:

spring.cloud.consul.config.prefixes[0]=config
spring.cloud.consul.config.format=YAML
spring.cloud.consul.config.default-context=application
spring.cloud.consul.config.watch.enabled=true
spring.cloud.consul.config.watch.delay=3000
spring.cloud.consul.config.watch.wait-time=5
spring.cloud.consul.config.fail-fast=true
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.query-passing=true
logging.level.org.springframework.amqp.rabbit.connection.CachingConnectionFactory=WARN

#---
spring.config.activate.on-profile=docker
spring.rabbitmq.host=rabbitmq

#---
spring.config.activate.on-cloud-platform=kubernetes
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
